# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Sendgrid
notify:
  - name: roland_email
    platform: sendgrid
    api_key: !secret sendgrid_token
    sender: home@lukacsroland.com
    recipient: !secret email_roland
  - name: petra_email
    platform: sendgrid
    api_key: !secret sendgrid_token
    sender: home@lukacsroland.com
    recipient: !secret email_petra

# Influxdb
influxdb:
  api_version: 1
  host: 192.168.1.3
  username: !secret influx_user
  password: !secret influx_password
  database: db0
  include:
    entities:
      - binary_sensor.entrance_door_1
      - binary_sensor.livingroom_motion_1
      - light.bathroom_ceilinglight_1

# Yeelight
discovery:
  ignore:
    - yeelight
yeelight:
  devices:
    192.168.1.20:
      name: Bathroom ceiling light
      model: ceiling4
    192.168.1.21:
      name: Living room ceiling light 1
      model: ceiling4
    192.168.1.23:
      name: Living room ceiling light 2
      model: ceiling4
    192.168.1.22:
      name: Bedroom ceiling light 1
      model: ceiling4
    192.168.1.24:
      name: Kitchen ceiling light 1
      model: ceiling4
    192.168.1.25:
      name: Lobby ceiling light 1
      model: ceiling4

# Binary sensors
binary_sensor:
  - platform: ping
    name: livingroom_television
    host: 192.168.1.13
    count: 3
    scan_interval: 10
  - platform: template
    sensors:
      livingroom_television_sensor:
        friendly_name: "Samsung TV"
        value_template: "{{ is_state('binary_sensor.livingroom_television', 'on') }}"
  - platform: template
    sensors:
      bathroom_washer_status:
        friendly_name: "Washer"
        value_template: >-
          {% if states('sensor.bathroom_washing_power_1') | float > 0 %}
            On
          {% else %}
            Off
          {% endif %}
  - platform: template
    sensors:
      bathroom_dryer_status:
        friendly_name: "Dryer"
        value_template: >-
          {% if states('sensor.bathroom_dryer_power_1') | float > 0 %}
            On
          {% else %}
            Off
          {% endif %}
  - platform: template
    sensors:
      kitchen_dishwasher_status:
        friendly_name: "Dishwasher"
        value_template: >-
          {% if states('sensor.kitchen_dishwasher_power_1') | float > 0 %}
            On
          {% else %}
            Off
          {% endif %}
  - platform: template
    sensors:
      kitchen_oven_status:
        friendly_name: "Cooked hood"
        value_template: >-
          {% if states('sensor.kitchen_cookerhood_power_1') | float > 0 %}
            On
          {% else %}
            Off
          {% endif %}

sensor:
  - platform: template
    sensors:
      livingroom_window:
        friendly_name: "Living room window"
        value_template: >-
          {% if is_state('binary_sensor.livingroom_window_1_bottom', 'on') and is_state('binary_sensor.livingroom_window_1_up', 'on') %}
            Opened
          {% elif is_state('binary_sensor.livingroom_window_1_bottom', 'off') and is_state('binary_sensor.livingroom_window_1_up', 'on') %}
            Half-Opened
          {% elif is_state('binary_sensor.livingroom_window_1_bottom', 'off') and is_state('binary_sensor.livingroom_window_1_up', 'off') %}
            Closed
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.livingroom_window_1_bottom', 'on') and is_state('binary_sensor.livingroom_window_1_up', 'on') %}
            mdi:window-open-variant
          {% elif is_state('binary_sensor.livingroom_window_1_bottom', 'off') and is_state('binary_sensor.livingroom_window_1_up', 'on') %}
            mdi:window-open
          {% elif is_state('binary_sensor.livingroom_window_1_bottom', 'off') and is_state('binary_sensor.livingroom_window_1_up', 'off') %}
            mdi:window-closed
          {% endif %}

# Inputs
input_select:
  livingroom_ac_mode:
    name: Mode of AC
    options:
      - Auto
      - Cool
      - Dry
      - Fan
      - Heat
    initial: Auto

# Light groups
light:
  - platform: group
    name: Living room lights
    entities:
      - light.livingroom_ceiling_light_1
      - light.living_room_ceiling_light_2

# Switches
switch:
  - platform: template
    switches:
      bathroom_ceiling_moonlight:
        friendly_name: Bathroom moonlight
        value_template: "{{ is_state('binary_sensor.bathroom_ceilinglight_1_nightlight', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.bathroom_ceilinglight_1_nightlight', 'on') %}
            mdi:lightbulb-on
          {% else %}
            mdi:lightbulb-off
          {% endif %}
        turn_on:
          service: yeelight.set_mode
          data:
            entity_id: light.bathroom_ceilinglight_1
            mode: moonlight
        turn_off:
          service: yeelight.set_mode
          data:
            entity_id: light.bathroom_ceilinglight_1
            mode: normal
      livingroom_ceiling_1_moonlight:
        friendly_name: Living room moonlight 1
        value_template: "{{ is_state('binary_sensor.livingroom_ceiling_light_1_nightlight', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.livingroom_ceiling_light_1_nightlight', 'on') %}
            mdi:lightbulb-on
          {% else %}
            mdi:lightbulb-off
          {% endif %}
        turn_on:
          service: yeelight.set_mode
          data:
            entity_id: light.livingroom_ceiling_light_1
            mode: moonlight
        turn_off:
          service: yeelight.set_mode
          data:
            entity_id: light.livingroom_ceiling_light_1
            mode: normal
      livingroom_ceiling_2_moonlight:
        friendly_name: Living room moonlight 2
        value_template: "{{ is_state('binary_sensor.living_room_ceiling_light_2_nightlight', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.living_room_ceiling_light_2_nightlight', 'on') %}
            mdi:lightbulb-on
          {% else %}
            mdi:lightbulb-off
          {% endif %}
        turn_on:
          service: yeelight.set_mode
          data:
            entity_id: light.living_room_ceiling_light_2
            mode: moonlight
        turn_off:
          service: yeelight.set_mode
          data:
            entity_id: light.living_room_ceiling_light_2
            mode: normal
      bedroom_ceiling_moonlight:
        friendly_name: Bedroom moonlight
        value_template: "{{ is_state('binary_sensor.bedroom_ceiling_light_1_nightlight', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.bedroom_ceiling_light_1_nightlight', 'on') %}
            mdi:lightbulb-on
          {% else %}
            mdi:lightbulb-off
          {% endif %}
        turn_on:
          service: yeelight.set_mode
          data:
            entity_id: light.bedroom_ceiling_light_1
            mode: moonlight
        turn_off:
          service: yeelight.set_mode
          data:
            entity_id: light.bedroom_ceiling_light_1
            mode: normal
      kitchen_ceiling_moonlight:
        friendly_name: Kitchen moonlight
        value_template: "{{ is_state('binary_sensor.kitchen_ceiling_light_1_nightlight', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.kitchen_ceiling_light_1_nightlight', 'on') %}
            mdi:lightbulb-on
          {% else %}
            mdi:lightbulb-off
          {% endif %}
        turn_on:
          service: yeelight.set_mode
          data:
            entity_id: light.kitchen_ceiling_light_1
            mode: moonlight
        turn_off:
          service: yeelight.set_mode
          data:
            entity_id: light.kitchen_ceiling_light_1
            mode: normal
      lobby_ceiling_moonlight:
        friendly_name: Lobby moonlight
        value_template: "{{ is_state('binary_sensor.lobby_ceiling_light_1_nightlight', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.lobby_ceiling_light_1_nightlight', 'on') %}
            mdi:lightbulb-on
          {% else %}
            mdi:lightbulb-off
          {% endif %}
        turn_on:
          service: yeelight.set_mode
          data:
            entity_id: light.lobby_ceiling_light_1
            mode: moonlight
        turn_off:
          service: yeelight.set_mode
          data:
            entity_id: light.lobby_ceiling_light_1
            mode: normal
  - platform: broadlink
    mac: "24:DF:A7:E4:8A:4F"
    switches: 
      - name: livingrooom_ac
        command_on: "JgBkAWMAASYTDhIwERAREBEQERAREBEQERARMBIPEg8SMBEQERARMREwETERMBIwERAREBEQERAREBEQERAREBEQERAREBEQERAREBEPEg8SDxEQERAREBEQERAREBEQERAREBEQERAREBEQERAREBIvETERMREwEmFkAAElEjASDxEQERASDxEQERAREBEQETASDxIPEjAREBIwETASMBExETARMREQERAREBEQEg8REBEPERESDhIPEg8SDxIPERAREBEQERAREBEQERAREBEQERAREBEQERAREBEQERAREBEPEhARDxIPEg8SDxJAYwABJxEwEg8REBEQERAREBEQERAREBExERAREBEwERARMREwEg8SMBIwETARMRExETARMREwEg8SDxIPEjARMREwERAREBEQERAREBEQERAREBIwETAREBExETASDxIPEg8SDxEQERAREBEQEjARMBIwETERAA0FAAA="
        command_off: "JgBkAWIAAScREBExERARDxIPEg8SDxEQERARMREQERARMBIuExARMREwETERMREwERAREBEQERAREBEQERAREBEQERAREBEQERAREBEQERAREBEPEg8SDxEQERAREBEQERAREBEQERAREBEQERAREBEQERARMBIvEmJkAAElEjAREBEQERAREBEQEg8REBEQETAREBEQETEREBEwEjASMBIvETERMREQEQ8SDxIPEg8SDxIPERAREBEQEg8REBEQERAREBEQERAREBEQERAREBEQERAREBEQEQ8SDxIPEg8REBEQERAREBEQERAREBFSYgABJxIvEhARDxIPEg8REBIPERAREBExERAREBEQETARMRExERARMBExETASMBExETASMBIwERAREBEQETARMREwEg8SDxIPEg8SDxEQERAREBExETASDxIwERARMREwERAREBEQERAREBEQERAREBExETARAA0FAAA="

# Alerts
alert:
  bathroom_light:
    name: Bathroom ceiling light is still on
    done_message: Bathroom ceiling light is off
    entity_id: light.bathroom_ceilinglight_1
    state: 'on'
    repeat: 60
    can_acknowledge: true
    skip_first: true
    notifiers:
      - roland_email
      - petra_email
  entrance_door:
    name: Entrance door is still open
    done_message: Entrance door is closed
    entity_id: binary_sensor.entrance_door_1
    state: 'on'
    repeat: 10
    can_acknowledge: true
    skip_first: true
    notifiers:
      - roland_email
      - petra_email



